[package]
name = "least"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
ratatui = "0.30.0-beta.0"

[lints]
clippy.pedantic = { level = "warn", priority = -1 }
